lsp:
  server:
    type: docker
    subtype: image # Or image. container subtype means launching an existing container
    # image subtype means creating a new container each time from a specified image
    name: duckdb_dev:latest  # customized image name
    container-name: duckdb-container
    docker-server-id: my-clangd-docker-3
    server: clangd # Server id of a registered server (by lsp-mode)
    launch_command: "clangd-14" # Launch command of the language server
    # (selected by a server id specified above) in stdio mode
    # Note: launch_command is not used with container subtype servers
    # as a command is embedded in a container itself and serves as an entrypoint
  mappings:
    - source: "/Users/korenhe/repo/duckdb"
      destination: "/workspace/duckdb"
